name: Checkmarx SCA Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can adjust the Java version as needed
        distribution: 'adopt' # Provide the required distribution input
        maven-version: 'latest' # This will install the latest Maven version

    - name: Set Maven Home
      run: echo "M2_HOME=/usr/bin" >> $GITHUB_ENV

    - name: Verify Maven Installation
      run: mvn -version


    - name: Check Maven Installation
      working-directory: ${{ github.workspace }} # Set the working directory to the root of the repository
      run: |
        mvn_location=$(which mvn)
        echo "Maven is installed at: $mvn_location"
#    - name: Set Maven Home
#      run: echo "M2_HOME=$(mvn -v | grep 'Maven home' | sed -E 's/Maven home: (.*)/\1/')" >> $GITHUB_ENV

#    - name: Set Maven Home
#      run: |
#        echo "M2_HOME=$(mvn -v | grep 'Maven home' | sed -E 's/Maven home: (.*)/\1/')" >> $GITHUB_ENV
   # - name: Download and Extract ZIP
   #   run: |
   #     curl -o file.tar.gz https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
   #     tar -xzvf file.tar.gz
        
   # - name: Show Extraction Path
   #   run: pwd
  
   # - name: List Directory Contents
   #   run: ls -al
    
   # - name: Set Permissions
   #   run: chmod -R 777 .
      
   # - name: List Directory Contents
   #   run: ls -al
        
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4 # GitHub Action version
      with:
        project: ${{ secrets.CHECKMARX_PROJECT }}  # <-- Insert Checkmarx CxSCA Project Name
        sca_api_url: https://eu.api-sca.checkmarx.net
        sca_app_url: https://eu.sca.checkmarx.net
        sca_access_control_url: https://eu.platform.checkmarx.net
        sca_tenant: EU-Support  # <-- Insert Checkmarx CxSCA Tenant
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sca
        
          
          
          
        bug_tracker: Sarif
        params: --sca.enable-sca-resolver=true --sca.sca-resolver-add-parameters.log-level=Debug --checkmarx.include-sources=false --namespace=${{ github.repository_owner }} --checkmarx.settings-override=true --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --repo-url="<GitHubRepoUrl>" --cx-flow.filterSeverity --cx-flow.filterCategory --logging.level.com.checkmarx.*=DEBUG

