name: Execute CX Flow

on:
  push:
    branches:
      - main

jobs:
  execute_cx_flow:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

#    - name: Set up JDK
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'  # You can specify the Java version you need here

#    - name: Install Java
#      run: |
#        sudo apt-get update
#        sudo apt-get install default-jre
#        sudo apt-get install default-jdk

    - name: Run CX Flow
      run: java -jar "D:\CxFlow\cx-flow-1.7.0.jar" --spring.config.location="${{ github.workspace }}\sca.yml" --scan --f="${{ github.workspace }}" --app="DVWA"
